version: '3'

tasks:
  build:
    cmds:
      - bash ./scripts/build.sh
      - cp ./bin/babel $GOBIN

  try_new:
    cmds:
      - go run . new

  start-weaviate:
    cmds:
      - bash ./scripts/start-weaviate.sh
    env:
      OPENAI_API_KEY: "{{.OPENAI_API_KEY}}"
  
  stop-weaviate:
    cmds:
      - bash ./scripts/stop-weaviate.sh
  
  stop-remove-weaviate:
    cmds:
      - bash ./scripts/stop-remove-weaviate.sh